### ISSUE TITLE
Live 11 support

### ISSUE THREAD

**Issue by laimison** [lucianoiam/live_rpyc#5]
Hey,

Anyone has an idea how these scripts can be updated to support Live 11?
What exactly in a code should be replaced, any possible roadmap?

Is there any tool that works on Live 11, not exactly live_rpyc? Maybe it's somehow similar to take ideas from them?

Thanks

**Comment by laimison** [comment]
I don't have an understanding how similar LiveOSC is, but they adding Live 11 support https://github.com/ideoforms/AbletonOSC . Is there some similarity comparing with live_rpyc? I would prefer live_rpyc if it can support Live 11.

**Comment by laimison** [comment]
Do you have an idea how much time needed for a Python developer to refractor the code with Live 11 support? Any random range to understand its size?

**Comment by lucianoiam** [comment]
If I correctly recall this project was started for Live 9 and then worked for 10 with minimal or no effort (do not remember exactly). But since the Live API is really not public the effort level can really range from negligible to several hours depending on your luck. Debugging can be painful and time consuming.

The original codebase comes from a hackaton held by Ableton in 2014, there is some good information [here](https://github.com/bkillenit/AbletonAPI/blob/master/python-api-materials/slides.pdf).

**Comment by lucianoiam** [comment]
Starting Live from a terminal allows to read any errors thrown by the built-in Python interpreter:

`/Applications/Ableton\ Live\ 10\ Suite.app/Contents/MacOS/Live `

**Comment by laimison** [comment]
Thanks mate, I'm now curious enough to watch the log and as a minimum report failed lines here OR try to fix error if I understand what is going on.

**Comment by lucianoiam** [comment]
Live 10 ships with Python 2.7, maybe Live 11 upgraded to Python 3?
https://stackoverflow.com/questions/33715579/python-3-module-itertools-has-no-attribute-ifilter

**Comment by laimison** [comment]
Seems it is working dude! https://github.com/lucianoiam/live_rpyc/pull/6 I've tested song tempo change successfully using same `client.py`

**Comment by lucianoiam** [comment]
Fixed in https://github.com/lucianoiam/live_rpyc/commit/de2ee5bd2d52da7e4a83491bb66dd89ec6f709c6
